### ISSUE TITLE
Fork Mailnag

### ISSUE THREAD

**Issue by tikank** [tikank/mailnag#1]
### Purpose
Since it seems that [Mailnag](https://github.com/pulb/mailnag) is [not currently maintained](https://github.com/pulb/mailnag/issues/251), and I want to continue use it while the world (Python, Gnome, Linux, everything…) changes, I will fork the Mailnag project and merge and fix things at least so much that the program is usable.

I know some parts of the code reasonable well, while other parts are not so familiar to me. I have been contributed to Mailnag and I think I can maintain this fork as much that it works for me and hopefully for others. I have no schedule when I fix or release something. It is released when it is ready.

If Mailnag gets maintained again in future, I hope that changes from this fork can be merged back to it. Otherwise the fork will live its own life.

### Visio
The first forked version of Mailnag is released.
Some tasks that the work will contain:
- [x] Some major fixes are merged to master.
- [x] News file is updated to contain overview of the changes.
- [x] The name of the project is changed so that it indicates that this is the fork of Mailnag.
- [x] setup.py is updated.
- [x] Readme file is updated.
- [x] About dialog is updated.
- [x] Authors file is updated.
- [x] ...
- [x] New version is released.

**Comment by tikank** [comment]
Merging following pull requests:
* https://github.com/pulb/mailnag/pull/250 - just to get unit tests working
* https://github.com/pulb/mailnag/pull/249 - Fixes maildir bug https://github.com/pulb/mailnag/issues/224 
* https://github.com/pulb/mailnag/pull/232 - Fixes Python 3.12 related issues for IMAP https://github.com/pulb/mailnag/issues/244 and https://github.com/pulb/mailnag/issues/245

**Comment by tikank** [comment]
### Name
Since I don't know if Mailnag is maintained in future, I want to avoid confusion using same name. And also I want to indicate that this is fork of Mailnag. So I will changed the name.
I don't want to invent totally different name because this is essentially same program. I also don't like name like Mailnag2 or so.

Let the name be **Mailnagger**. It is something that nags mails...
It is different from Mailnag but reasonable close to it.

I am not going to change name everywhere in code, at least now. Only in mailnag --> mailnagger, mailnag-config --> mailnagger-config, in GUI and in readme etc. files.

**Comment by mfreeman72** [comment]
Good to see you're forking this! I was afraid we had seen the last of mailnag. Since you say you're not yet familiar with parts of the program, are you up to doing bug fixes if I report one?

**Comment by tikank** [comment]
@mfreeman72, please do report. I see what I can do when I can.

**Comment by mfreeman72** [comment]
Done! Thanks! Let me know if you need anything else from me. I've also got some *very* minor coding experience in Python, JavaScript, and C++, that could stand to use a little more experience, and would love to help in any way I can, with this or any other interesting projects.

**Comment by tikank** [comment]
Oh well. Learning to use Github: [Detaching a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork ).
So, to make independent detached repository, I will rename this clone back to name mailnag and create a new repository for [mailnagger](https://github.com/tikank/mailnagger). Let's see what kind of mesh I can create...
I will track these three issues here but then new issues should be opened to the new mailnagger repository.
